### ISSUE TITLE
Trouver un logo

### ISSUE THREAD

**Issue by barbogogo** [barbogogo/leedReader#15]

**Comment by ghost** [comment]
Je veux bien me proposer pour un logo. J'ai déjà créé et redessiné le logo de Leed pour mon thème, je peux te fournir le fichier si tu veux :-)

**Comment by barbogogo** [comment]
Tu proposes un logo pour l'application ?
Je n'ai pas eu le temps de lire les quelques recommandations pour la réalisation d'un logo pour android...
http://developer.android.com/design/style/iconography.html

**Comment by ghost** [comment]
Dès que le design de l'application sera figé ce sera plus simple. Ou je peux te fournir la version orange du logo de Leed en le faisant correspondre aux recommandation Android... à toi de choisir ;-)

**Comment by barbogogo** [comment]
Dans ce cas, on attend que le design de l'application soit figé. Mais le [logo orange](https://github.com/misterair/HotBeer/blob/master/logo.png) que tu as fait me plait bien ;-)

**Comment by ghost** [comment]
tu peux t'en servir, il est là pour ça ;-)

**Comment by barbogogo** [comment]
Ok, merci ;-)
Est-ce que tu pourrais me le donner en 144x144 px ?

**Comment by ghost** [comment]
voilà: ![leedlogo](https://f.cloud.github.com/assets/4334834/854925/93d65ba8-f512-11e2-88d4-439f83f32e36.png)

**Comment by barbogogo** [comment]
Merci ;-)
