### ISSUE TITLE
pouvoir lire les flux en mode déconnecté

### ISSUE THREAD

**Issue by cobalt74** [barbogogo/leedReader#17]
suite à la connexion, récupérer les flux non lu et naviguer en mode hors connexion.

**Comment by barbogogo** [comment]
Salut Cobalt,
Excellente idée. Je regarde quelle solution serait la mieux faire et te tiens au courant.
Barbogogo

**Comment by cobalt74** [comment]
OK. Super sinon la petite appli ;-)

**Comment by barbogogo** [comment]
Salut Cobalt,
Une solution est trouvée : Stockage des données via SQLite.
La solution est en cours de développement.
Barbogogo

**Comment by cobalt74** [comment]
Super fait signe pour les tests ;)
Objectif : tout charger a la connexion !

**Comment by barbogogo** [comment]
Hello,
La première version est disponible [sur le site](http://www.barbogogo.fr/leedreader-en-mode-off-line-demarrage-des-tests/).
Barbogogo

**Comment by cobalt74** [comment]
ok j'ai mis la nouvelle version à jour, j'ai bien le Online mais par contre quand j'enlève le wifi, je clic sur un article et l'application s'arrête brusquement.

**Comment by barbogogo** [comment]
Salut Cobalt,
Merci pour ton retour.
Ok... c'est seulement en ouvrant un article ?

**Comment by cobalt74** [comment]
pour info : je suis sur tablette nexus 7.
non ce n'est pas que sur un article, c'est aussi dans la navigation. Dès que je suis en offline paf l'appli s'arrête.

**Comment by barbogogo** [comment]
Salut Cobalt,
Je n'arrive pas à reproduire le problème.
Est-ce que tu vois le message "Téléchargement terminé" ?
Si tu cliques sur "OffLine" tu peux revenir en mode "OnLine" puis en mode "GetData". Est-ce que tu as essayé de télécharger une seconde fois les données ou est-ce que l'application n'arrive plus à se lancer ?

**Comment by cobalt74** [comment]
Effectivement je n'avais pas compris le fonctionnement !
Donc le bug c'est uniquement quand tu es en online et que tu coupe le wifi.
Sinon en off line c'est OK. Manque les images quand pas de connexion
Et pas encore de synchro entre élément lus en off line et remise en mode on line.
Sinon bien ;)

**Comment by barbogogo** [comment]
Ok, merci du retour.
Bug à corriger : Perte de la connexion en mode OnLine.
Oui, il n'y a pas encore la synchro, c'est prévu très bientôt (comme une barre de téléchargement) ;-)
Merci pour ton retour.

**Comment by barbogogo** [comment]
Cobalt,
Peux-tu essayer le fichier suivant : [LeedReader_offline_b0.2.apk](http://barbogogo.fr/xplorer/data/public/f45fa18c16c4ed10f545584b38ce2e7e.php?lang=fr)
Il permet de vérifier la présence du réseau de données en mode OnLine.
https://github.com/barbogogo/leedReader/tree/a9015b9268e8ae416ac950b2c5a3f19cacef84b2

**Comment by cobalt74** [comment]
je test ça ce soir ;)

**Comment by cobalt74** [comment]
Mode online sans connexion, sa marche sur la navigation dossier. Un message s'affiche lorsque je clic sur un flux (genre vous n'êtes pas connecté) et l'application s'arrête. 
Mais j'ai bien un message qui s'affiche brièvement !

**Comment by barbogogo** [comment]
Salut Cobalt,
Merci pour ton retour.
Tu as un message, mais l'application s'arrête... ce n'est pas terrible --> création de l'issue https://github.com/barbogogo/leedReader/issues/19.
Je regarde ça !
ps: désolé mon Galaxy est HS, je ne peux pas tout tester... je n'ai que l'émulateur qui est assez limité...
Je te tiens au courant ;-)

**Comment by cobalt74** [comment]
pas de problème. ;)
c'est déjà fonctionnel

**Comment by barbogogo** [comment]
Bonjour,
Une mise à jour est disponible [sur le site](http://www.barbogogo.fr/leedreader-en-mode-off-line-quelques-corrections/).
Barbogogo

**Comment by barbogogo** [comment]
Bonjour,
Les fonctionnalités nécessaires pour une utilisation Off Line sont implémentées (sauf le téléchargement des images).
La dernière révision est disponible sur ce lien : http://www.barbogogo.fr/leedreader-en-mode-off-line-de-nouvelles-corrections/
Toutefois, je ne ferme pas encore cette issue. Celle-ci sera fermée en même temps que le merge de la branche OffLine avec le master.

**Comment by cobalt74** [comment]
nice ça marche ;)

**Comment by cobalt74** [comment]
je continue les remontées sur cet issue tant que ce n'est pas sur la branche principale.

Lorsque je suis en mode offline, je met à lu quelques articles, puis je repasse en mode online.
j'ai ce message dans l'encart noir de message (End of input character of 0)

Rien de bloquant.

**Comment by barbogogo** [comment]
Ok merci ;-)

**Comment by barbogogo** [comment]
Salut @cobalt74,
J'ai généré la révision [LeedReader_offline_b0.5.apk](http://barbogogo.fr/xplorer/data/public/2357e8a9b790c1851dcc25fc4b239fa4.php?lang=fr) qui supprime l'encart noir et améliore légèrement les performances.

**Comment by cobalt74** [comment]
Faut mettre la dernière API ?

**Comment by barbogogo** [comment]
Non, il faut laisser l'ancienne version.

**Comment by barbogogo** [comment]
Branche OffLine fusionnée dans le master.
Toutefois, il reste l'amélioration #22 pour une utilisation plus complète du mode OffLine (à ce jour, seul le texte est téléchargé).

**Comment by cobalt74** [comment]
;)
