### ISSUE TITLE
Fermeture intempestive en mode OnLine sur perte du réseau de données

### ISSUE THREAD

**Issue by barbogogo** [barbogogo/leedReader#19]
Voir commentaire de Cobalt https://github.com/barbogogo/leedReader/issues/17#issuecomment-18290216

**Comment by cobalt74** [comment]
yop j'ai toujours le problème de fermeture lorsque je simule la perte de connexion en mode online.
version 0.3beta.
est ce qu'il y a un moyen de mettre des logs sur android que je pourrais te remonter ?

**Comment by barbogogo** [comment]
Salut,
Ok, noté.
Merci pour ton retour.
Je ne sais pas exactement comment activer les logs. Il me semble qu'il faut se mettre en mode développeur.

**Comment by barbogogo** [comment]
Salut Cobalt,
C'est corrigé dans la nouvelle révision.
http://www.barbogogo.fr/leedreader-en-mode-off-line-de-nouvelles-corrections/
