### ISSUE TITLE
Crash de l'application sur dossier vide

### ISSUE THREAD

**Issue by gbour** [barbogogo/leedReader#21]
Bonjour,

Si je clique sur un dossier vide (écran principal de leedreader), l'application crashe.

Guillaume.

**Comment by barbogogo** [comment]
Bonjour Guillaume,

Merci pour ton retour.

**Comment by barbogogo** [comment]
Bug corrigé intégré dans le master

**Comment by gbour** [comment]
merci @barbogogo
