### ISSUE TITLE
Contrôle plugin API activé

### ISSUE THREAD

**Issue by cobalt74** [barbogogo/leedReader#26]
Je me suis fais avoir, j'ai remplacé le plugin API et du coup, il était désactivé :)
Sur Leed-Reader, message d'erreur technique.

Est ce que tu peux detecter si le plugin est non installé ? et donc renvoyer un message du grenre "Erreur : Plugin API désactivé" pour les boulets comme moi :p

**Comment by barbogogo** [comment]
Salut @cobalt74,
Si le plugin n'est pas activé il y a un message d'erreur qui devrait apparaitre "API disabled".
Par contre si le plugin n'est pas installé, il y a une erreur 404 qui s'affiche avec la page paramètre qui apparait. Par contre, ce n'est peu être pas très explicite...

**Comment by cobalt74** [comment]
Hello @barbogogo 
pardon il était installé et non activé

**Comment by barbogogo** [comment]
@cobalt,
Tu as fait un ré-installation complete? Ou juste une mise à jour partielle de quelques fichiers?

**Comment by cobalt74** [comment]
réinstall complète.

**Comment by barbogogo** [comment]
@cobalt74, ok merci.

Il manque un contrôle dans la mise à jour de l'API.
Ouverture du ticket https://github.com/barbogogo/leed-API/issues/7

**Comment by cobalt74** [comment]
ok. je clos celui là.
