### ISSUE TITLE
Impossible de charger les flux

### ISSUE THREAD

**Issue by ghost** [barbogogo/leedReader#31]
J'ai voulu tester cette application, mais impossible de récupérer les flux depuis l'application. 
Je suis sous Android 2.2 et Leed 1.5.

**Comment by barbogogo** [comment]
Bonjour @misterair,
Est-ce que tu as bien installé l'[API](http://www.barbogogo.fr/projets/applications-leed/leed-api/telechargement/) ?
Si oui, l'as-tu activée (dans la partie plugins)?
Quelle révision de LeedReader as-tu installée ?
Barbogogo

**Comment by ghost** [comment]
La dernière version de l'API et LeedReader, à savoir API 0.4 et LeedReader 0.9.
L'API est bien activé comme tu l'as indiqué dans le ReadMe.

**Comment by ghost** [comment]
J'ai ré-installé l'API et LeedReader, toujours impossible de récupérer les articles. La connexion se passe bien mais je l'application Android m'indique "Get Data" et reste bloquée sur "initialisation".

**Comment by barbogogo** [comment]
Ok. Pour réutiliser l'application, il faut que tu supprimes les données via le menu paramètres d'Android.

Lorsque tu navigue en mode OffLine, tout se passe bien ?

**Comment by barbogogo** [comment]
Ok. Pour réutiliser l'application, il faut que tu supprimes les données via le menu paramètres d'Android.

Lorsque tu navigues en mode OnLine, tout se passe bien ?

**Comment by ghost** [comment]
J'ai supprimé les donnés comme tu m'as indiqué, et en mode OnLine je n'ai rien du tout. L'application ne semble rien récupérer comme données

**Comment by barbogogo** [comment]
A l'ouverture de l'application, tu devrait avoir la liste de tes répertoires...
Tu as un message qui apparait ?
Tu as bien au moins un répertoire de flux ? :-/

**Comment by ghost** [comment]
nop, les répertoires ne s'affichent pas. impossible de les charger.
En gros une fois la connexion réussie j'ai une page blanche avec en haut à gauche une icône de maison, un joli "online" qui se transforme en "get data" quand je clique dessus, et en haut à droite un icône censé afficher le chargement de l'application mais qui tourne dans le vide. 
Complètement inutilisable en somme :-(

**Comment by barbogogo** [comment]
Ok, la connection ne doit pas bien se faire, une détection de l'activation 3G ou WiFi est faite, mais il n'y a pas de test réalisé pour un délai de réponse avec le serveur. Est-ce que tu arrives à naviguer sur ton site leed avec ton mobile?
Sinon, je vais mettre à disposition la semaine prochaine la révision 1 de LeedReader. J'espère que ce problème sera résolu avec cette nouvelle révision...

**Comment by ghost** [comment]
je peux accéder à mon site via le navigateur sans trop de soucis, webkit sous Android 2.2 étant une catastrophe...
J'attends avec impatience cette future version alors ;-)

**Comment by barbogogo** [comment]
Ok. 
- [x] Il faut que j'ajoute quelques vérifications notamment sur le temps de réponse du serveur...

**Comment by barbogogo** [comment]
Création du ticket : https://github.com/barbogogo/leedReader/issues/33 pour le futur

**Comment by grimlokason** [comment]
Bonjour,

Je rencontre le même soucis de blocage lors du chargement.
Accès en web : ok
Android 4.1.2
testé en wifi et 3g : ko
suppression des données et reconfig idem.

Je suis dispo pour faire des tests si besoin !

Merci !

**Comment by barbogogo** [comment]
Bonjour @grimlokason,

Merci pour ce retour.

Quelle version de Leed utilisez-vous ?

**Comment by grimlokason** [comment]
J'ai tenté avec la version 1.5 puis une version dev. les 2 avec le même résultat.
Parcontre, mon serveur est sur un mutualisé OVH... je vais tout rapatrier en local pour tester
Il y aurait des prérequis php par exemple ?

**Comment by barbogogo** [comment]
Les prérequis sont :
- Serveur Apache conseillé (non testé sur les autres serveurs types Nginx…)
- PHP 5.3 minimum
- MySQL

J'ai fait un test avec :
- la version 1.5 de Leed (https://github.com/ldleman/Leed/tree/1cfb27b748f1bec132a2c1e613df097e3d2fa3f2),
- la version 0.4 de l'API (http://www.barbogogo.fr/projets/applications-leed/leed-api/telechargement/)
- la version 0.9 de l'application (http://www.barbogogo.fr/projets/applications-leed/leedreader/telechargement/)
  et ça a fonctionné.

**Comment by grimlokason** [comment]
Même erreur en local.
Aurais-tu un Leed de test qu'on puisse vérifier si ça viens de nos config Leed ou de nos android ?

**Comment by barbogogo** [comment]
Un site de test est disponible : 
- url : http://rss.barbogogo.fr
- login : barbogogo
- mot de passe : barbogogo

**Comment by grimlokason** [comment]
Ça fonctionne avec ton site de test.

**Comment by barbogogo** [comment]
Peux-tu faire un site de test sur ton serveur pour que je regarde ?
Quelle est ta version de php ?

**Comment by grimlokason** [comment]
j'ai la 5.3 sur les 2 serveurs

Une session de test : 

Url : http://grim-is-a-geek.fr/Leed-barbo
login : barbogogo
mot de passe : barbogogoLogin

**Comment by grimlokason** [comment]
mince, c/c loupé : 
mot de passe : barbogogo

**Comment by ghost** [comment]
@grimlokason impossible de récupérer les données sur ta session test...

@barbogogo  ta session test fonctionne sur mon smartphone. Par contre pas moyen d'afficher les articles en online comme offline. En mode online l'Application plante... la faute à Android 2.2?
J'ai aussi un hébergement mutualisé mais chez 1&1. Ma version de php est la 5.4.

**Comment by barbogogo** [comment]
@grimlokason J'ai une erreur de connexion, le login est bien barbogogo et le mot de passe barbogogo ?
Est-ce que tu arrives à lire les articles ?

@misterair, Apparemment, il ne devrait pas y avoir de problème de compatibilité avec Android 2.2... tu arrives à naviguer dans tes répertoires ?

**Comment by grimlokason** [comment]
@barbogogo : je viens de voir plusieurs messages comme ça dans mes log apache sur mon serveur local.
[Mon Jul 29 21:16:35.064485 2013] [:error] [pid 30058:tid 140068027045632] [client 192.168.1.125:37981] PHP Notice:  Use of undefined constant JSON_UNESCAPED_UNICODE - assumed 'JSON_UNESCAPED_UNICODE' in /var/www/localhost/htdocs/Leed/plugins/api/json.php on line 84
Cette fonction semble n'exister qu'a partir de php 5.4.

Quand je passe à la version 5.5, j'obtiens un message sur l'android "value <br of type java.lang.string cannont be converted to jsonobject' et quelques page ou j'utilisais du json ne fonctionne plus.. 
Je vais donc installer PHP 5.4 pour tester ^^'

Sinon les login/mdp sont bien barbogogo et j'arrive à voir les articles avec.

**Comment by grimlokason** [comment]
Je viens de passer en 5.4 sur mon serveur local, ça fonctionne sur android.
Parcontre, le passage en 5.4 sur le mutualisé ne résout pas le soucis. je comparerais demain les conf php.

à demain !

**Comment by barbogogo** [comment]
@grimlokason merci pour ces informations. J'avais zappé ce problème de compatibilité. Par contre, je n'arrive toujours pas à me connecter à ton site de test.

@misterair puis-je avoir plus d'informations sur ta config utilisée. Lorsque j'essaie de faire tourner l'application sur Android 2.2, l'application plante. Quelle version de LeedReader utilises-tu ?

**Comment by barbogogo** [comment]
@misterair peux-tu essayer avec [LeedReader-v0.7](http://barbogogo.fr/xplorer/data/public/1d8f9ba5fef1ff1f229d45f1ac9c76fd.php?lang=fr) ?
Si ça marche, je mettrai à jour l'application avec les dernières mises à jour, tout en gardant la compatibilité.

**Comment by grimlokason** [comment]
Bizarre votre soucis d'accès, ptet un bug à cause d'un cookies lier à ma session.

Modification du compte :
Url : http://grim-is-a-geek.fr/Leed-barbo
login : test
mot de passe : test

**Comment by ghost** [comment]
@barbogogo la version 0.9 plante de temps en temps en effet. Je ne peux pas te donner plus d'infos que la version de php, ça reste un hébergement mutualisé, donc je ne gère pas tout. Mais Leed 1.5 stable fonctionne sans soucis.

Par contre la version 0.7 de LeedReader est incapable de se connecter, elle m'indique toujours "url invalide". Problème de communication avec l'API 0.4 ?

**Comment by barbogogo** [comment]
@misterair l'API 0.4 est compatible avec LeedReader 0.7...
Désolé de t'embêter, mais peux-tu essayer [LeedReader-v0.8](http://barbogogo.fr/xplorer/data/public/3369dcbe496e1fa7b825e0952eb7df77.php?lang=fr), c'est juste pour voir quelle version peut être compatible (en espérant qu'il y en ait une...).

**Comment by ghost** [comment]
@barbogogo la version 0.8 se comporte exactement comme la version 0.9. Toujours ce problème de connexion. Je pense que tu devrais rester sur ce que tu as cité là: https://github.com/barbogogo/leedReader/issues/31#issuecomment-21626294

**Comment by barbogogo** [comment]
@misterair le problème c'est que la nouvelle révision n'est pas compatible avec Android 2.2... j'essaie donc de voir sur quelle ancienne version je peux faire une branche pour cette version d'Android.
Il me semble que 1and1 est en php 5.2.17. Tu peux avoir l'information en faisant un phpinfo() dans un fichier php.

**Comment by grimlokason** [comment]
@misterair, tu ne peu pas récuperer ta config php grâce à çette fonction ? : 
phpinfo();

**Comment by barbogogo** [comment]
@misterair je me suis mélangé les pinceaux... [LeadReader v0.7](http://barbogogo.fr/xplorer/data/public/1d8f9ba5fef1ff1f229d45f1ac9c76fd.php?lang=fr) n'est pas compatible avec l'API v0.4, mais est compatible avec l'[API v0.2](https://github.com/barbogogo/leed-API/tree/8b1b3b1c31a95065784ed4149b71fa25fd2fa204). Vu ta config, peux-tu essayer ?

**Comment by ghost** [comment]
@barbogogo l'API v0.4 ne change rien, toujours ce message d'erreur: "url invalide".

@grimlokason bonne question, va falloir que je creuse ça et apprenne ne connaissant rien au php une fois sorti de Wordpress...

**Comment by grimlokason** [comment]
Bon, il y a pas mal de différence entre les 2 config pour la même version de php... -_-'
1ère piste les "Registered PHP Streams": 
Celui qui fonctionne :
compress.zlib, compress.bzip2, dict, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtsp, scp, sftp, smtp, smtps, telnet, tftp, php, file, glob, data, phar, zip
Celui qui est KO : 
https, ftps, compress.zlib, compress.bzip2, php, file, glob, data, http, ftp, phar, zip

Savez vous comment les activer via htaccess ?

@misterair en mettant juste cette fonction dans une page php entre les 2 balise php, tu aura toute la config php... il y a plein d'info, voir même trop...

**Comment by barbogogo** [comment]
@grimlokason @misterair merci pour ces informations. Je vais regarder tout cela de très près, il est important de voir les configurations compatibles et de développer en conséquence. Il est dommage que le couple LeedReader v0.7 - l'API v0.2 ne fonctionne pas. Je vous tiens au courant.
Merci pour votre aide.

**Comment by barbogogo** [comment]
@misterair en effet, le couple LeedReader v0.7 - l'API v0.2 est incompatible (d'où le message "url invalide").
Si 1and1 a bien la version php 5.2.17, l'application tournait dans le vide à cause d'une erreur php qui bloquait la génération de la page et donc pas de retour de la part du serveur.
peux-tu essayer [cette version de l'API](https://github.com/barbogogo/leed-API/tree/leed-api-v0.2). J'ai créé une branche pour être compatible avec php 5.2. Par contre, tu risque d'avoir des caractères étranges...
Cette API est compatible avec [LeedReader v0.6](http://barbogogo.fr/xplorer/data/public/6db7108609a10c19771fabf021fec7c2.php?lang=fr). Les tests que j'ai réalisés sont concluants (API installée sur http://rss.barbogogo.fr, login : barbogogo, mot de passe : barbogogo).

**Comment by barbogogo** [comment]
@grimlokason pour les "Registered PHP Streams", j'ai exactement la même configuration que celle qui est KO pour toi... donc ça ne vient pas de là.
En faisant un phpinfo(), est-ce que tu as bien les modules json, mysql et session ?
Quelles sont les erreurs dans les logs ?

**Comment by grimlokason** [comment]
@barbogogo 
 Pour mes info php du serveur KO : 

json support    enabled
json version    1.2.1 

MySQL Support   enabled
Active Persistent Links     0
Active Links    0
Client API version  5.1.61
MYSQL_MODULE_TYPE   external
MYSQL_SOCKET    /var/run/mysqld/mysqld.sock
MYSQL_INCLUDE   -I/usr/include/mysql
MYSQL_LIBS  -L/usr/lib -lmysqlclient 

Session Support     enabled
Registered save handlers    files user memcache
Registered serializer handlers  php php_binary wddx

Directive   Local Value Master Value
session.auto_start  Off Off
session.cache_expire    180 180
session.cache_limiter   nocache nocache
session.cookie_domain   no value    no value
session.cookie_httponly Off Off
session.cookie_lifetime 0   0
session.cookie_path /   /
session.cookie_secure   Off Off
session.entropy_file    no value    no value
session.entropy_length  0   0
session.gc_divisor  1000    1000
session.gc_maxlifetime  1440    1440
session.gc_probability  0   0
session.hash_bits_per_character 5   5
session.hash_function   0   0
session.name    PHPSESSID   PHPSESSID
session.referer_check   no value    no value
session.save_handler    files   files
session.save_path   /tmp    /tmp
session.serialize_handler   php php
session.upload_progress.cleanup On  On
session.upload_progress.enabled On  On
session.upload_progress.freq    1%  1%
session.upload_progress.min_freq    1   1
session.upload_progress.name    PHP_SESSION_UPLOAD_PROGRESS PHP_SESSION_UPLOAD_PROGRESS
session.upload_progress.prefix  upload_progress_    upload_progress_
session.use_cookies On  On
session.use_only_cookies    Off Off
session.use_trans_sid   1   1

J'ai pas accès aux log de mon taf. Je te dit ça ce soir.

**Comment by grimlokason** [comment]
Bon, j'ai trouvé les logs,

J'ai rien dans les erreurs et ceci dans les accès : 
109.190.39.15 grim-is-a-geek.fr - [31/Jul/2013:21:02:41 +0200] "GET /Leed/plugins/api/login.php HTTP/1.1" 401 46 "-" "Android-4.1.2/LeedReader-1.0"
109.190.39.15 grim-is-a-geek.fr - [31/Jul/2013:21:02:42 +0200] "GET /Leed/plugins/api/login.php HTTP/1.1" 401 46 "-" "Android-4.1.2/LeedReader-1.0"
109.190.39.15 grim-is-a-geek.fr - [31/Jul/2013:21:02:56 +0200] "GET /Leed/plugins/api/login.php HTTP/1.1" 401 46 "-" "Android-4.1.2/LeedReader-1.0"
109.190.39.15 grim-is-a-geek.fr - [31/Jul/2013:21:02:56 +0200] "GET /Leed/plugins/api/login.php HTTP/1.1" 401 46 "-" "Android-4.1.2/LeedReader-1.0"

Je chercherais demain comment augmenter la verbosité

**Comment by barbogogo** [comment]
@grimlokason on voit une erreur 401 qui correspond à une erreur de connexion digest.
Cette erreur correspond bien à l'erreur de connexion que j'ai en essayant de me connecter. Cette erreur est envoyée par la fonction `function auth_request($realm)` du fichier [auth.php](https://github.com/barbogogo/leed-API/blob/master/api/auth.php) de l'API. Par contre, je ne comprends pas cette erreur...

Salut @gbour, est-ce que tu peux regarder ce problème de connexion et donner une piste stp ?

**Comment by ghost** [comment]
@barbogogo API 0.2 et LeedReader 0.6 ça marche! par contre il n'y a pas de mode offline...
Petit rappel: je suis sous php5.4 et non php 5.2 ;-)

**Comment by barbogogo** [comment]
Salut @misterair, ok, j'étais parti sur du php 5.2... si tu es vraiment sur du php 5.4, je vais sortir une révision 0.10 avec la remontée des erreurs php et on regardera plus en détails les erreurs qui te sont remontées...
merci pour ton retour ;-)

**Comment by grimlokason** [comment]
@barbogogo, la nouvelle API me sort une erreur sur le fichier json.php.

Quand je l'ouvre dans firefox, j'ai ceci : 
{"error":{"id":"3","message":"PHP error: Note[8]Undefined index: option- /homez.527/grimisag/www/Leed/plugins/api/json.php(l30)"}}
{"error":{"id":"0","message":"no error"}}

sur le serveur qui fonctionne :
<br />
<b>Notice</b>:  Undefined index: option in <b>/home/raistlin/www/Leed/plugins/api/json.php</b> on line <b>27</b><br />
{"error":{"id":"0","message":"no error"}}

**Comment by barbogogo** [comment]
@grimlokason, merci pour ce retour.
Je vois deux problèmes :
- Au niveau de l'API: les erreurs PHP ne sont pas très bien gérées puisque tu arrives à avoir la partie json {"error":{"id":"0","message":"no error"}}.
- Au niveau de l'application : à l'initialisation, la variable option n'est pas initialisée.

Du coup, j'ai modifié l'API et l'application...
Tu pourras les trouver :
- [API](https://github.com/barbogogo/leed-API/tree/d24a9d377b23c2f819a2895c1e8c8a1b78d16e22)
- [Application](http://barbogogo.fr/xplorer/data/public/b35ea20ac2ce27e0f6b111c17d932774.php?lang=fr)

Désolé et mille mercis pour tes retours et ta persévérance !

**Comment by grimlokason** [comment]
@barbogogo 

Avec cette api : 
{"error":{"id":"3","message":"<h1>PHP Error</h1><p>Note[8]Undefined index: option- /homez.527/grimisag/www/Leed/plugins/api/json.php(l30)</p><p>Your server configuration:</p><ul><li>PHP Version: 5.3.16</li><li>JSON Version: 1.2.1</li><li>MySQL Version: 1.0</li></ul>"}}

On va y arriver :D

**Comment by barbogogo** [comment]
@grimlokason est-ce que tu as installé l'[application v1.1](http://barbogogo.fr/xplorer/data/public/b35ea20ac2ce27e0f6b111c17d932774.php?lang=fr) ?

**Comment by grimlokason** [comment]
@barbogogo j'obtiens un login failed via l'interface.

et j'obtiens le même résultat via le navigateur si je vais sur http://grim-is-a-geek.fr/Leed/plugins/api/login.php, il me demande en boucle mes identifiants

**Comment by barbogogo** [comment]
Salut @grimlokason, 
Tu me donnes une nouvelle piste et il semble que ça peut payer : apparemment la gestion d'authentification par digest n'est pas très stable... Je regarde de plus près et je te tiens au courant.

**Comment by barbogogo** [comment]
@grimlokason fausse alerte, la gestion par digest est bonne.
Il est impossible de se connecter via le navigateur car le mot de passe est haché (sha1). L'authentification par l'application se fait donc avec un mot de passe haché alors que via le navigateur, le mot de passe est en clair.
Il faut que je regarde pour mettre un bout de code qui vérifie où ça ne fonctionne pas et pourquoi...

**Comment by cobalt74** [comment]
hello @barbogogo, j'ai un login failed à la connexion. Tout ça me parait indigeste :smile:

**Comment by barbogogo** [comment]
Salut @cobalt74.
Très beau jeu de mots sur ce sujet qui me donne plein de maux...
On dirait que ça ne marche que chez moi grrr...
Je fais une dernière tentative puis je crois que je vais désactiver l'authentification par digest...

**Comment by cobalt74** [comment]
@barbogogo j'avoue ne rien y paner tel un poisson rouge (au bout de 3 sec je sèche)
bref vive les mots de passe en claire pour les applications perso :) bon ok je sors. :hand:

**Comment by barbogogo** [comment]
@cobalt74 tu as peut etre une partie de la réponse... comment sont hachés les mots de passe dans Leed (pardon, j'ai ma flemme de fouiller le code...)

**Comment by cobalt74** [comment]
dans le fichier action.php cherche le case sur login.

et après, $user = $userManager->exist($_['login'],$_['password']);
dans User.class.php tu as le contenu de la fonction

**Comment by cobalt74** [comment]
il y a une protection des variables aussi dans le common.php

//Récuperation et sécurisation de toutes les variables POST et GET
$_ = array();
foreach($_POST as $key=>$val){
$_[$key]=Functions::secure($val, 2); // on ne veut pas d'addslashes
}
foreach($_GET as $key=>$val){
$_[$key]=Functions::secure($val, 2); // on ne veut pas d'addslashes
}

**Comment by barbogogo** [comment]
@grimlokason @cobalt74 Je crois que j'ai trouvé : il semblerait que ce soit au niveau de l'encodage des caractères.
Leed encode dans sa base de données en utf8_general_ci alors que l'application Android en UTF-8.
Du coup lors du hash du mot de passe, le résultat est différent lors d'une utilisation de caractères spéciaux (comme le &).
Pouvez-vous confirmer que vous utilisez des caractères spéciaux dans votre mot de passe ? Si oui, pouvez-vous le changer et refaire un test ?
Merci :smile:

**Comment by cobalt74** [comment]
Pas de caractère spéciaux pour mon mdp. Désolé.

**Comment by barbogogo** [comment]
@cobalt74 juste des chiffres et des lettre non accentuées ?

**Comment by cobalt74** [comment]
ouep minuscule/majuscule/chiffre

**Comment by grimlokason** [comment]
@barbogogo  
Tout en minuscule, même les chiffres !
Mot de passe et identifiant sans caractères spéciaux et court :  login failed

**Comment by barbogogo** [comment]
@cobalt74 @grimlokason Pouvez-vous faire une petite vérification (désolé je tâtonne).
Pouvez-vous installer cette [version de LeedReader](http://barbogogo.fr/xplorer/data/public/2107bcedf2f30899d4b751377ae36f86.php?lang=fr), puis après avoir rentré vos identifiant cliquer sur "getPsw" dans le menu.
Vous obtiendrez le mot de passe en clair (attention, cachez votre écran) et le mot de passe hashé.
Pouvez-vous comparer ce hash avec ce qui est dans la base de données, dans la table user ?
Merci pour votre collaboration.

**Comment by grimlokason** [comment]
@barbogogo j'ai bien le même hash

**Comment by barbogogo** [comment]
@grimlokason @cobalt74, j'ai réaliser une version permettant de remonter la raison de l'erreur de l'authentification. Peux-être que cela pourra nous aider.
Pour ce faire, il faut télécharger [LeedReader-v1.2](http://barbogogo.fr/xplorer/data/public/73a9e69d9c082a3826ab73e9baf6833b.php?lang=fr) et [Leed-API v0.7](https://github.com/barbogogo/leed-API/tree/3f6ffd6b50fce16fc0ddb48ebb97b10fbc2d7df4).
Désolé que ça prenne autant de temps, et merci pour votre collaboration ! :smile:

**Comment by cobalt74** [comment]
@barbogogo voici le message 

**Login failed**
Digest vide

je modifie mon message, je vais comparer le hash
Comparaison ok, j'ai le bon hash mais le message ci dessus

**Comment by cobalt74** [comment]
@barbogogo info importante, ça marche avec mon environnement de dev sur mon nas.
mais ne fonctionne pas avec mon environnement de production (Hébergement OVH)

Est ce que le truc indegest ne serait pas à activer sur ces hébergements ! :)

**Comment by cobalt74** [comment]
je suis sur la piste du module mod_headers que je n'ai pas sur OVH et qui ressort sur mon NAS dès que je fais un appel à l'application.

**Comment by grimlokason** [comment]
@barbogogo j'ai le même résultat que cobalt74

@cobalt74 tu es aussi sur un mutualisé ovh ?, pro ou perso ?
Il semble que le mod_headers est présent sur les pro.
Sais-tu comment activer les modules ?

**Comment by cobalt74** [comment]
@grimlokason sur un perso pour l'instant.
Je ne sais comment l'activer désolé. A chercher sur le forum d'OVH.
Je n'ai pas pu avancer sur mes tests mais @barbogogo va nous trouver une solution :+1:

**Comment by barbogogo** [comment]
Bonjour messieurs,
J'ai chercher quelques pistes pour activer mod_headers via un .htaccess, mais il semblerait que ce ne soit pas possible...
Du coup, une authentification par deux moyens sera proposée:
- une via digest (solution par défaut ? avec un message d'erreur précis si mod_headers n'est pas installé),
- l'autre plus simple, en envoyant le sha1 du mot de passe vers l'API qui le comparera avec le mot de passe stocké dans la base de données.

Pour la seconde solution, j'utiliserai le bout de code donné par @cobalt74 précédemment.

Merci à vous ( @grimlokason et @cobalt74 ) pour vos retours.

**Comment by barbogogo** [comment]
Messieurs,
J'ai terminé la mise à jour de LeedReader et de l'API pour que le choix du mode d'authentification soit possible.
Par défaut, j'ai préféré ne pas passer par le mode Digest. Le mot de passe est donc hashé (sha1) puis envoyé vers l'API.
Vous pourrez trouver [LeedReader-v1.3](http://barbogogo.fr/xplorer/data/public/786ccc.php) (j'espère que la v1.5 sera également la bonne) et [Leed-API-v0.8](https://github.com/barbogogo/leed-API/tree/ae6e0fbaab7013a46c7d6be631dfc52a15c2274e).

**Comment by grimlokason** [comment]
@barbogogo ça fonctionne :D

**Comment by barbogogo** [comment]
@grimlokason cool :smile:

**Comment by cobalt74** [comment]
C'est good ;)

(pour la version multi user)
pour finir sur l'authentification, si on change de user, il ne recharge pas complètement les objets. On doit quitter l'application et la relancer pour que l'environnement de l'utilisateur soit correctement chargé.

**Comment by barbogogo** [comment]
@cobalt74, merci pour ces informations.
La version multi-user est la prochaine étape, mais j'ai déjà une petite idée :smile:

**Comment by cobalt74** [comment]
ça marche déjà mais c'est juste qu'il faut quitter l'appli et la relancer pour correctement charger l'environnement

**Comment by barbogogo** [comment]
Peux-tu essayer l'[appli suivante](http://barbogogo.fr/xplorer/data/public/a966a5.php) ?

**Comment by cobalt74** [comment]
Nickel :)

**Comment by barbogogo** [comment]
Cool :smile:
les sujets de @cobalt74 et @grimlokason sont donc clos.

@misterair, je ne t'ai pas oublié :smile:

**Comment by ghost** [comment]
@barbogogo vraiment dommage que tu sois obligé de créer une 2e branche pour les version anciennes d'Android. :/

**Comment by barbogogo** [comment]
@misterair pas de problème !

Pour récapituler :
Tu as la configuration suivante :
- Adroid 2.2
- Leed 1.5
- Leed-API 0.4
- LeedReader 0.9
- PHP 5.4

Symptomes :
- En mode OffLine, l'application tourne dans le vide, seulement "Initialisation" est affiché à l'écran.
- En mode On Line, l'application tourne dans le vide

Lors de l'utilisation de LeedReader 0.6 avec Leed-API 0.2, tout fonctionne.
Ce couple permet une connexion sans Digest. Je pense que c'est un problème similaire à @cobalt74 et @grimlokason.

Je vais donc repartir de LeedReader-v0.9 pour adapter à Leed-API-v0.8 et gérer les deux modes d'authentification.

Je te tiens au courant :smile:

**Comment by barbogogo** [comment]
@misterair, peux-tu essayer le couple [LeedReader v0.10](http://barbogogo.fr/xplorer/data/public/f4a777.php) et [Leed-API v0.8](https://github.com/barbogogo/leed-API/tree/ae6e0fbaab7013a46c7d6be631dfc52a15c2274e) ?

**Comment by ghost** [comment]
c'est possible d'avoir un version déjà compilée de LeedReader v0.10 stp ?

**Comment by barbogogo** [comment]
oups : [LeedReader v0.10](http://barbogogo.fr/xplorer/data/public/0a89e7.php)
Je t'ai donné le bon fichier, mais j'ai oublié l'extension...

**Comment by ghost** [comment]
joli boulot! mode online et offline fonctionnels! il n'y a que le mode d'identification "Digest" qui fait planter l'Application si j'essaie de l'activer.

**Comment by barbogogo** [comment]
Cool si tout marche :smile: 

Le mode digest fait planter l'application ?
intéressant... je vais regarder ça...

**Comment by ghost** [comment]
tu vas pouvoir enfin plancher sur le design et l'implémentation d'autres fonctionnalités surtout ;-)

**Comment by barbogogo** [comment]
Le design, c'est fait avec la v1, mais elle n'est pas compatible avec android 2.2...
Pour les autres fonctionnalités, si tu as des idées ;-)

**Comment by ghost** [comment]
j'espère un jour changer de smartphone ça serait une solution aussi :D 
Pour les fonctionnalités tout à été dit il me semble. Il n'y a que le bouton de synchronisation qui manque vraiment.

**Comment by barbogogo** [comment]
Toutefois, on peut essayer de tendre vers ce que tu as proposé : https://github.com/barbogogo/leedReader/issues/27#issuecomment-21554102

**Comment by ghost** [comment]
ce serait top, mais il ne faut pas que ça te donne trop de travail

**Comment by barbogogo** [comment]
On va voir. Par contre, je suis intéressé par les icones que tu as utilisée ;-)
Si elles sont libres d'utilisation, je veux bien les récupérer pour l'application ;-)

**Comment by ghost** [comment]
ce ne sont pas vraiment des icônes c'est une [Font](http://mfglabs.github.io/mfglabs-iconset/)

**Comment by barbogogo** [comment]
Parfait ;-)
Merci
