### ISSUE TITLE
Url non valide depuis passage v1

### ISSUE THREAD

**Issue by agentcobra** [barbogogo/leedReader#35]
Bonjour,
depuis le passage en V1, 
j'ai url invalide et l'application se ferme toute seule en mettant que "LeedReader s'est arrêté". 
Pourtant l'url est valide http://192.168.19.1/leed/

Ma configuration :
- serveur 
  - Synology DS413j
    - Apache/2.2.23
    - PHP 5.3.21
    - MySQL 5.1.49 
  - Leed version 1.5 Beta
- leed-api en version 0.5
- client
  - Android 4.1.2 (galaxy note 2)

_note : en revenant sous LeedReader 0.9 ça refonctionne_

**Comment by barbogogo** [comment]
Bonjour @agentcobra,
Merci pour ce retour.
Est-ce que as essayé le couple LeedReader 0.9 - Leed-API 0.5 ? 
Est-ce que tu as bien mis le "http://" devant le lien ?
Ton url pointe sur une IP locale. Etais tu bien connecté à ton réseau local ?

**Comment by barbogogo** [comment]
@agentcobra,
Peux-tu ajouter le numéro de port dans ton url ?
http://192.168.19.1:80/leed/
Il semblerait que la fonction HttpGet puisse être sensible...

**Comment by agentcobra** [comment]
@barbogogo, tu as pas vu ma petite note.
Le problème persiste en ajoutant le port.
Je suis bien connecté sur mon lan, sinon j'arriverai pas à utiliser l'application github sur mon note 2 :)

**Comment by agentcobra** [comment]
J'ai remis sans le port, il me le prends en compte mais lors du changement, il plante

**Comment by barbogogo** [comment]
@agentcobra peux-tu essayer [cette appli](http://barbogogo.fr/xplorer/data/public/aa1dc80a3b8defb8368ea752c4bcf036.php?lang=fr), j'ai ajouté du code qui permet de remonter les erreurs rencontrées.
Peux-tu me faire un retour quant à l'erreur remontée (en espérant que ça marche) ?

**Comment by agentcobra** [comment]
J'ai rien de plus, j'ai un écran de chargement puis un écran blanc puis plantage

**Comment by barbogogo** [comment]
Bonjour @agentcobra,
Peux-tu essayer [LeedReader-v1.3](http://barbogogo.fr/xplorer/data/public/786ccc.php) avec [Leed-API-v0.8](https://github.com/barbogogo/leed-API/tree/ae6e0fbaab7013a46c7d6be631dfc52a15c2274e).
Il y a une meilleur surveillance des erreurs...

**Comment by agentcobra** [comment]
j'ai mis à jour les 2, le problème d'url à l'air résolu mais j'ai toujours l'application qui crash.
j'ai vider les données de l'app sur l'android pour partir d'une installe fraiche et rerentrer les infos. j'ai pas touché à l'option de l'auth. :unamused:

**Comment by barbogogo** [comment]
Peux-tu me donner un accès Leed (soit tu fais une nouvelle install, soit tu me donne un login / mote de passe) ?
Je voudrais tester en debug avec le [SDK](http://fr.wikipedia.org/wiki/SDK).

**Comment by agentcobra** [comment]
:mailbox:

**Comment by barbogogo** [comment]
Lorsque tu as réinitialisé les données de l'application, le mode de connexion pour l'authentification était sur Basic ?

**Comment by agentcobra** [comment]
Oui en basic

**Comment by barbogogo** [comment]
Est-ce que tu utilises le port 80 ?

**Comment by agentcobra** [comment]
oui, j'utilise le port 80

**Comment by barbogogo** [comment]
Ok, je viens de voir qu'il pouvait y avoir des plantages si le serveur ne répondait pas assez rapidement.
Aujourd'hui, la limite est mise à 10s, après tout explose... c'est étrange...
Je vais voir ce sujet de plus près.
Je te tiens au courant :smile:

**Comment by agentcobra** [comment]
ok, merci pour votre aide, n'hésitez pas à me demander de tester d'autres apk ou api ;)
(pour la connexion distante, il faut que je whitelist votre adresse ip (cf :mailbox: ))

**Comment by barbogogo** [comment]
Bonjour @agentcobra,
Pouvez-vous essayer [LeedReader-v1.3.2](http://barbogogo.fr/xplorer/data/public/83a3b0.php) avec [Leed-API-v0.8](https://github.com/barbogogo/leed-API/tree/ae6e0fbaab7013a46c7d6be631dfc52a15c2274e) ?
Merci :smile:

**Comment by agentcobra** [comment]
![screenshot_2013-08-09-17-24-09](https://f.cloud.github.com/assets/1831853/938894/78a2962e-0108-11e3-86cc-9ae437d6a70e.png)

**Comment by barbogogo** [comment]
Bonjour,
Il semblerait que le serveur n'écoute pas sur ce port...
Est-ce que la connexion nécessite un certificat (https, ...) ?
Il me semble que le problème vienne du serveur.

**Comment by agentcobra** [comment]
Il est bien sur le port 80.
Après redémarrage du nas + service httpd + maj leed
Le problème est corrigé.

**Comment by barbogogo** [comment]
@agentcobra parfait :smile: 
Bonne lecture !
