### ISSUE TITLE
Permettre la synchronisation des flux

### ISSUE THREAD

**Issue by barbogogo** [barbogogo/leedReader#36]
Ajouter l'option de synchronisdtion de flux sur le serveur Leed.

**Comment by barbogogo** [comment]
héhé ça marche.
Par contre, je vais faire un peu de css et rendre le code plus propre :smile: 

![synchronisation](https://f.cloud.github.com/assets/4095207/933662/fc4fcf04-005a-11e3-92dc-549c4e4c0fb4.png)

Rendez-vous demain pour la fonction disponible sur LeedReader-v0.X et LeedReader-v1.X

**Comment by barbogogo** [comment]
@grimlokason, @misterair, @cobalt74,
La synchronisation est disponible avec [LeedReader-v1.3.2](http://barbogogo.fr/xplorer/data/public/83a3b0.php) et [LeedReader-v0.10.1](http://barbogogo.fr/xplorer/data/public/d2759c.php).

**Comment by cobalt74** [comment]
yop, synchro ok. par contre, j'ai eu un plantage de l'appli suite à la synchro, quand je suis allé sur le menu cachédes flux et cliqué sur un flux.

**Comment by ghost** [comment]
la synchro fonctionne pour LeedReader-v0.10.1.
par contre c'est normal que lorsque je glisse un article vers la droite ou la gauche ça marque le dossier comme lu?

**Comment by barbogogo** [comment]
Normalement, ça ne met que l'article comme lu... je vérifie.

**Comment by barbogogo** [comment]
@cobalt74, c'est corrigé avec le push [dc35f51b72](https://github.com/barbogogo/leedReader/tree/dc35f51b72b10377868d1362b8c0a2c736e3ba76)

**Comment by barbogogo** [comment]
@misterair, c'est corrigé avec le push [2d03da4d2c](https://github.com/barbogogo/leedReader/commit/2d03da4d2c3588d8daa803be80d9a05e00491561)

**Comment by ghost** [comment]
ok.
J'ai remarqué que le version 0.10 à aussi le problème du retour au menu lors d'un passage du mode portrait/paysage

**Comment by barbogogo** [comment]
Oui, https://github.com/barbogogo/leedReader/issues/38 ;-)

**Comment by ghost** [comment]
voilà ^^

Et est-ce possible d'avoir une entrée "partage" dans le menu de la version 0.10? ce serait sympa et pratique :-)

**Comment by barbogogo** [comment]
Yep, elle existe sur la v1, mais il y a une incompatibilité majeure pour l'utiliser en v0...
Je regarde comment développer ça manuellement.

**Comment by barbogogo** [comment]
Fonction ajoutée dans le commit https://github.com/barbogogo/leedReader/commit/6e763049d528534e6187d00e8399afd5c1270be5

**Comment by ghost** [comment]
Petit détail: tu peux ajouter un retour automatique à la page d'accueil après la synchronisation? comme le logo peut-il être cliquable et rendre à cette page d'accueil?

Il manque aussi l'affichage des pages par catégories comme sur la version Web de Leed.

**Comment by barbogogo** [comment]
Oui, il est possible de faire en sorte que l'on retourne automatiquement vers la page d'accueil après une synchronisation avec un petit message "Synchronisation terminée". Toutefois, dans un premier temps, j'ai préféré afficher le statut de la synchronisation. Peut être que certains préféreront le retour automatique et d'autres l'affichage du statut de la synchronisation... Cela peut être un paramètre à configurer dans les préférences... #53

Le logo est cliquable et permet aujourd'hui d'afficher le menu.

Il faut que je regarde comment afficher les catégories, plutôt que les répertoires #54.
