### ISSUE TITLE
Site du projet down

### ISSUE THREAD

**Issue by qwertygc** [barbogogo/leedReader#39]
Bonjour,
je souhaite utiliser cette app. Malheureusement, le site du projet, pour le télécharger, semble avoir du mal à ce connecter. Possibilité d'avoir l'APK + le leed-API par ailleurs ? Merci

**Comment by barbogogo** [comment]
Bonjour,
Le site est de nouveau opérationnel. Désolé pour ce contre temps.
L'appli est encore en beta et des bugs ont été remontés. Merci pour vos retours.

**Comment by qwertygc** [comment]
Merci. Petite suggestion : Avoir l'article complet sous les yeux et non cliquer sur le lien pour le lire. Voilà :)
