### ISSUE TITLE
Blank page issue

### ISSUE THREAD

**Issue by ldleman** [barbogogo/leedReader#4]
@barbogogo Once the server address back into the application, I get a blank page and nothing happens.

It is surprising that the application never asks me the password or login, I wonder how she could retrieve data

**Comment by barbogogo** [comment]
@ldleman Yes, when you save the link to the server, please click on the "Get Information" button in order to ask the server.
The leed application does no really need a login and a password to get data. However, it is a possible enhancement, not for security reason, but for multi account...

**Comment by ldleman** [comment]
I've clicked on it, but nothing happend...

Login and password should be integrated for security reason too, or anyone can see and update informations of each leed witch contain json.php...

**Comment by barbogogo** [comment]
Ok, I note the first point : you can not read your feeds from your server. It is a bug. Normally, if the address is not correct (404, ...) a new window appears to change the address of your server. The address shall be as "http://www.example.com/leed".
The second point concerns the necessity to be identified in order to navigate in your feeds. For me it is not urgent because the only one modification you can do is to set an article read or not read. However, I have open the issue #5.

**Comment by barbogogo** [comment]
Ok, the issue is due to the incompatibility since the modification of the "getFeedsPerFolder" function.
I have to update the [leed-API](https://github.com/barbogogo/leed-API).

**Comment by barbogogo** [comment]
Bonjour Idle,

Quel commit correspond la version de Leed sur ton
serveur ?

En téléchargeant le dernier commit, j'ai été surpris, la
présence des balises dans le corps de l'article n'était pas terrible,
...

Je pense qu'il faudrait travailler ensemble en faisant du
versioning. J'ai un fork Barbogogo/leed
(https://github.com/barbogogo/Leed), qui permet d'avoir une version de
leed compatible avec l'API, ainsi qu'un site de test :
http://rss.barbogogo.fr. A partir de ce site de test, l'application que
je t'ai envoyée devrait fonctionner.

Quel commit je peux prendre afin
de mettre à jour l'API ?
Le site sur lequel tu as fait des essais est
extrait de quel commit ?

Cordialement,

Barbo 

Le 2013-04-18 14:00,
Idleman a écrit : 

> I've clicked on it, but nothing happend... 
> 
> Login and password should be integrated for security reason too, or
> anyone can see and update informations of each leed witch contain
> json.php... 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> [1].

## Links:

[1]
https://github.com/barbogogo/leedReader/issues/4#issuecomment-16572391

**Comment by ldleman** [comment]
Yop !! (On passe au français :D ?)

De quelles balises parles tu ? Mon leed est régulièrement mis à jour via un pull sur le master de Leed, c'est sûr lui que je fais mes tests (rss.idleman.fr), le numéro de révision doit être l'avant avant dernier commit, mais je vais le mettre à jour aujourd'hui.

Concernant l'API, je pense qu'il faudrait plus l'intégrer en tant que plugin qu'en natif.

Je vais essayer avec le site de test pour te faire mes retours sur la partie typiquement appli :)

**Comment by barbogogo** [comment]
Issue moved to the [leed-API](https://github.com/barbogogo/leed-API).
https://github.com/barbogogo/leed-API/issues/1
