### ISSUE TITLE
Avoir l'article complet sous les yeux

### ISSUE THREAD

**Issue by barbogogo** [barbogogo/leedReader#42]
"Petite suggestion : Avoir l'article complet sous les yeux et non cliquer sur le lien pour le lire."
https://github.com/barbogogo/leedReader/issues/39#issuecomment-22490188

**Comment by barbogogo** [comment]
@qwertygc, j'ai fait un essai et je ne trouve pas ça très concluant.
C'est éventuellement intéressant pour des articles courts :
![sans titre](https://f.cloud.github.com/assets/4095207/956671/0f44ded4-0442-11e3-8f53-d4b5cf3332dc.png)

Par contre, pour des articles long, ce n'est pas très pratique.

Trouves-tu que la navigation entre les articles via un [swipe](http://developer.android.com/design/patterns/swipe-views.html) n'est pas satisfaisante ?
Je peux regarder pour insérer le début de l'article...

**Comment by qwertygc** [comment]
Bof. Au pire, une option paramétrable ?

**Comment by barbogogo** [comment]
Juste pour information, tu as quel type de support (téléphone, tablette, ...) et le modèle ?

**Comment by qwertygc** [comment]
Smartphone Sony Xperia U

**Comment by barbogogo** [comment]
Bonjour,

Afin de mieux se rendre compte, je vais t'envoyer un fichier apk pour tester et me dire ce que tu pense de la navigation.

**Comment by barbogogo** [comment]
Et voilà, à tester...
http://barbogogo.fr/xplorer/data/public/f491e4.php

**Comment by qwertygc** [comment]
C'est vachement mieux. Par contre, c'est possible d'avoir pas de marges ? Je te montre.
![screenshot_2013-09-02-12-16-09](https://f.cloud.github.com/assets/4261986/1066664/dd46fb5c-13b8-11e3-9a86-6c3454f506ad.png)
A droite et à gauche, ça serai possible de faire disparaitre ? width à 100% quoi.

**Comment by barbogogo** [comment]
Ces marges existent pour les boutons pour favoriser l'article ou le mettre en lu / non lu.
Cet affichage ne permet pas de mettre les articles comme lus automatiquement.

**Comment by barbogogo** [comment]
Trois mois sans échange = sujet clos.
