### ISSUE TITLE
Dossier

### ISSUE THREAD

**Issue by cobalt74** [barbogogo/leedReader#43]
Pouvoir charger les articles d'un dossier lorsqu'on clic sur le libellé ou sur le nombre.

**Comment by barbogogo** [comment]
Salut @cobalt74,
Tu parles vraiment du dossier ou seulement du titre du flux + le nombre d'articles non lus ?

Aujourd'hui, on ne peut voir que les articles du flux sélectionné en cliquant sur son libellé.
Il est possible d'ajouter la même fonctionnalité en cliquant sur le nombre d'articles non lus.

Il est également envisageable d'afficher les articles d'un dossier lorsque l'on clique sur son titre. Cette action permettrait d'afficher la hiérarchie du dossier et de charger les articles contenus dans le dossier. Aujourd'hui, le fait de cliquer sur un dossier n'affiche que la hiérarchie, sans afficher les articles du dossier (ensemble des articles contenus dans tous les flux du dossier).

**Comment by cobalt74** [comment]
Oui sur le dossier

**Comment by barbogogo** [comment]
Ok, ça marche, je vais regarder ça.
