### ISSUE TITLE
android 4.3 = plantage

### ISSUE THREAD

**Issue by tmos** [barbogogo/leedReader#45]
Salut,
J'ai installé l'application sur mon Nexus 4, avec la dernière version de Android (4.3, dernière mise à jour mineure incluse), et impossible de la lancer : au démarrage elle plante directement.

Mon téléphone est à disposition si besoin de tests :)

**Comment by barbogogo** [comment]
Salut @tmos,
Merci pour ce retour.
Arf, c'est ennuyeux, mille mercis pour ta collaboration !
En effet, sur une version Android 4.3, ça plante... je regarde ce qui se passe et je te tiens au courant...

**Comment by barbogogo** [comment]
@tmos, tu pêux essayer [LeedReader-v1.4](http://barbogogo.fr/xplorer/data/public/c18b7d.php) pendant que je me penche sur ce problème majeur...

**Comment by barbogogo** [comment]
@tmos, bug trouvé et normalement corrigé.
Peux-tu essayer [LeedReader-v1.4.2](http://barbogogo.fr/xplorer/data/public/f223b7.php).

Le bug touche toutes les personnes n'ayant pas paramétré LeedReader dans une version antérieure...

Encore merci !

**Comment by tmos** [comment]
ça marche ! Merci pour le fix rapide :)

**Comment by barbogogo** [comment]
Merci à toi pour le retour :smile:
