### ISSUE TITLE
Fonction de notification sur la disponibilité d’une nouvelle version indisponible

### ISSUE THREAD

**Issue by barbogogo** [barbogogo/leedReader#47]
Suite à la mise à jour de LeedReader-v1.4.2, la fonction de notification sur la disponibilité d’une nouvelle version n'est plus fonctionnelle.
Ceci est dû au manque d'initialisation d'une variable...

**Comment by cobalt74** [comment]
En voulant installer la 1.4.2, elle est indiqué 1.4.1beta sur le apk

**Comment by barbogogo** [comment]
Salut,
Oui, merci :smile:
