### ISSUE TITLE
Fonctionnement mode hors-ligne

### ISSUE THREAD

**Issue by kvnco** [barbogogo/leedReader#50]
Bonjour,

Ce ticket concerne plutôt une question qu'un rapport de bug.

J'utilise l'application depuis quelques jours, mais je ne parviens pas à saisir le fonctionnement du mode hors-ligne.
J'arrive bien à consulter les articles en étant déconnecté lorsque je sélectionne le mode hors-ligne. Ceux-ci sont bien marqué comme lu, dans l'application… mais comment ensuite synchroniser les billets lus avec le serveur ?

Merci

**Comment by barbogogo** [comment]
Bonjour,

Normalement, il suffit de revenir en mode en-ligne et la synchronisation se fait avec le serveur.
Tous les articles lus seront lus sur le serveur et tous les articles mis comme favoris seront mis comme favoris sur le serveur.

Si il y a un problème de synchronisation, n'hésite pas à faire un retour.

**Comment by kvnco** [comment]
Merci pour le retour.

Ce n'est effectivement pas le comportement que j'ai constaté jusqu'à
maintenant. Néanmoins, je vais refaire quelques tests avant d'en conclure à
un bug (j'ai ~ 500 flux, et je veux m'assurer que ce n'est pas un problème
de charge du serveur ou de connexion)…

Kevin

**Comment by barbogogo** [comment]
Ok, merci pour l'investigation et pour ton retour :smile:

**Comment by kvnco** [comment]
Hello,

Il semble bien qu'il y ait un soucis quelque part.

Voici le test fait
- j'ai d'abord identifié un item en le marquant d'abord comme lui puis non lu (pour récupérer son id)
- je suis ensuite passé en non-connecté, j'ai marqué cet item comme lu, puis en connecté pour voir ce qui se passait
- une requête est bien passée lors de la reconnexion mais elle est sans effet

"GET /plugins/api/json.php?option=setRead&idArticle=20485 HTTP/1.1" 200 58
(la taille de la réponse indiquerait un message d'erreur ?)
- si je marque ensuite ce ticket comme lu (en étant connecté), ça fonctionne (on note le fait que la réponse est plus courte)

"GET /plugins/api/json.php?option=setRead&idArticle=20485 HTTP/1.1" 200 32

Serait-ce un problème d'authentification faite ou non avant la requête ?

**Comment by barbogogo** [comment]
Salut,

Merci beaucoup pour ces détails qui m'ont permis d'aller très vite.
En effet, il y a un problème lié à l'identification. Avant la synchronisation, il faut faire une nouvelle authentification...

Bravo et merci :smile:

**Comment by kvnco** [comment]
À défaut d'avoir le temps d'installer le SDK et de mettre la main à la pâte
(mais ça viendra), j'essaie d'être un beta-testeur efficace ! :)

**Comment by barbogogo** [comment]
Et ça marche à la perfection :smile:

**Comment by kvnco** [comment]
Corrigé, merci !
