### ISSUE TITLE
Masquer les dossiers "vides"

### ISSUE THREAD

**Issue by kvnco** [barbogogo/leedReader#51]
Bonjour,

Puisque le choix est fait de ne pas récupérer sur LeedReader les flux lus, pourquoi ne pas masquer les dossiers/flux du menu ne contenant pas d'éléments non lus ?

**Comment by barbogogo** [comment]
Bonjour,

J'ai peur que ça déstabilise... ça permet de confirmer que tous les articles du répertoire sont lus.

A terme, il est prévu que les flux lus soient également récupérés.

**Comment by kvnco** [comment]
Alors peut-être que ça serait une option intéressante… en tous cas, lorsque
l'on a beaucoup de flux.

Kevin

**Comment by barbogogo** [comment]
Ok, je note : ajouter une option dans les paramètres permettant de masquer les répertoires lorsque tous les articles du répertoire sont lus.

Merci

**Comment by kvnco** [comment]
Merci ! :)
