### ISSUE TITLE
Lorsqu'une image comporte un texte au survol (attribut "title"), ajouter un champ le reprenant

### ISSUE THREAD

**Issue by kvnco** [barbogogo/leedReader#52]
Bonjour,

Voici une suggestion reprise d'une idée qui était implémentée sur Google Reader et que je juge assez utile.

Lorsqu'une image comporte un champ "title" (texte dont le contenu est affiché au survol), un champ est ajouté sous l'image, reprenant ce contenu.
Ex. : les illustrations du site xkcd
![9a104b08-d6d8-11e2-8d2e-ad1202a2c847](https://f.cloud.github.com/assets/2389101/1063875/5f1922ee-12f7-11e3-9213-6db9c5ae1817.png)

Cette option est utile pour les interfaces tactiles (ne permettant donc par le survol du curseur).

**Comment by barbogogo** [comment]
Bonjour,

Effectivement, cette fonctionnalité est très intéressante.

Merci :smile:

**Comment by kvnco** [comment]
J'ai écrit un bout de code JS qui fait ça que je voudrais proposer pour un pull-request dans Leed.
(elle parcourt les balises img et crée un div en dessous si celles-ci comporte un title)
Comment sont affichés les articles dans l'appli, ce serait intégrable également pour le reader ?

**Comment by barbogogo** [comment]
Bonjour,
Cette fonctionnalité serait directement gérée en Java avec une recherche à l'aide d'une expression régulière.
J'ai déjà utilisée cette option pour permettre d'ouvrir une vidéo Youtube à l'extérieur de LeedReader.

Toutefois, le code JS peut être intéressant comme base pour coder en Java.

**Comment by kvnco** [comment]
Je posterai un petit lien sur le pull request quand j'aurai finalisé mon travail (je me bats un peu avec le moteur de plugin de leed pour être honnête)…

**Comment by kvnco** [comment]
Hop : ldleman/Leed-market#65

**Comment by barbogogo** [comment]
Ok, je regarde ça :smile:

**Comment by kvnco** [comment]
Malheureusement, c'est du JS et je doute que ça aide bcp à faire qqc de bien en Java. J'essaierai pt-être de voir ce que je peux faire en Java si j'ai du temps pour !

**Comment by barbogogo** [comment]
Voici un premier résultat : 
![screenshot_2013-10-08-14-03-08](https://f.cloud.github.com/assets/4095207/1288633/d487b8a6-3011-11e3-8ce9-836aeb7555c3.png)

Ici, l'image est entourée par un lien (celui de l'image), c'est pourquoi l'encadré est souligné.
:smile:

**Comment by kvnco** [comment]
Hum… Pas mal du tout ! :)

**Comment by barbogogo** [comment]
J'ai un peu réduit la police de l'encadré, ce qui donne :
![screenshot_2013-10-08-17-42-40](https://f.cloud.github.com/assets/4095207/1290521/d6c23b08-3031-11e3-8975-8ec45c63dbfb.png)

**Comment by barbogogo** [comment]
Modification prise en compte, elle s'affiche pour le moment en permanence, à voir si on ajoute une option dans les préférences de l'application.

**Comment by kvnco** [comment]
Hello,

Je viens de tester la fonctionnalité sur le nouvel apk (1.4.6b) et je remarque que :
- un cartouche vide apparaît parfois (il faudrait détecter si l'image n'a pas de title ou que celui-ci est vide)
- l'application crash lorsque j'affiche un billet qui comporte une image avec un title non vide (j'utilise toujours le flux d'xkcd, par exemple, pour mes tests)

**Comment by kvnco** [comment]
Je corrige ce que j'ai dit plus haut.

Le cartouche vide apparaît à de très rares cas (à vrai dire, je n'ai pas encore identifié lesquels, c'est un bug très mineur).
Ce qui est bcp plus gênant c'est le crash qui apparaît lors de l'affichage de certains billets (pas tous).
J'ouvre un ticket à ce sujet…

**Comment by barbogogo** [comment]
@kvnco, tu confirmes que lorsque la balise `title` est vide, l'application plante ?

**Comment by barbogogo** [comment]
oups, je viens seulement de voir ton ticket #68... la réponse est donc oui...
