### ISSUE TITLE
Crash lors de la lecture d'un item

### ISSUE THREAD

**Issue by kvnco** [barbogogo/leedReader#56]
Bonjour,

Je constate depuis la dernière mise-à-jour (v 1.4.5b) quelques crash.
Ceux-ci ne sont pas systématiques, mais proviennent généralement lorsqu'assez rapidement après le lancement de l'application (alors que le chargement ne serait pas terminé ?), j'essaie d'afficher un item en cliquant dessus ou je le marque comme lu. L'application se ferme alors et une fenêtre indique « L'application "LeedReader" s'est arrêtée. ».
A priori, le bug n'est pas lié à un item en particulier.

À disposition si je peux effectuer d'autres tests qui aiderait à diagnostiquer l'erreur.

Pour information, j'utilise Android 4.1.1.

**Comment by barbogogo** [comment]
Bonjour @kvnco,
Merci pour ce retour.
Est-ce lié à un flux en particulier ?
Les articles non lus sont tout d'abord affichés, ensuite le menu.
A ton avis, est-ce que ce crash apparait lorsque tu cliques sur un item et que le chargement du menu n'est pas terminé ?

**Comment by kvnco** [comment]
Non, le bug ne semble lié ni à un flux ni à un item en particulier. Par contre il est effectivement possible que l'erreur apparaisse lorsque le menu n'est pas complètement chargé.
(comme ça se joue à quelques secondes près, je sais pas comment je peux le confirmer)

**Comment by barbogogo** [comment]
Ok, je vais faire des tests.
Merci :smile:

**Comment by barbogogo** [comment]
Je n'arrive pas à reproduire ce problème.
Est-ce que tu l'as de nouveau rencontré ?

**Comment by kvnco** [comment]
Je confirme que je peux reproduire cette erreur de façon systématique. Il suffit par exemple de marquer comme lu un billet d'un clic sur l'icône juste après le lancement.
L'erreur n'apparaît plus après quelques secondes, ce qui semble attester l'hypothèse d'un chargement qui n'est pas terminé.

Au besoin, je peux également effectuer des tests avec une autre configuration. :)

**Comment by barbogogo** [comment]
Ok, merci.
Maintenant, les articles s'affichent lorsque tout est chargé.

**Comment by barbogogo** [comment]
Salut @kvnco,

Si tu le souhaites, une mise à jour de l'application est [disponible](http://barbogogo.fr/xplorer/data/public/deaaf4.php) celle-ci prend en compte les modifications suite à nos derniers échanges.

**Comment by kvnco** [comment]
Hello,

Je l'ai téléchargée, et je suis en train de tester.
Il semble que ce bug n'existe plus ! Je close ! Merci :)

Par contre, j'ai d'autres remarques à faire… je vais commenter sur les pages qui correspondent.
