### ISSUE TITLE
Erreur API/serveur => timeout ?

### ISSUE THREAD

**Issue by kvnco** [barbogogo/leedReader#57]
Bonjour,

J'utilise régulièrement l'application « en mobilité » et il m'arrive très souvent lorsque j'utilise la connexion internet mobile que celle-ci m'affiche des erreurs indiquant soit une erreur d'API, soit que le serveur ne répond pas.
Pourtant la connexion DATA semble fonctionner convenablement et l'étude des logs sur le serveur ne montre rien d'anormal. Y a-t-il un timeout un peu sensible configuré quelque part ?

Il me semble (mais ça reste une impression) que ces erreurs sont plus nombreuses depuis la dernière mise-à-jour (v 1.4.5b).

À noter : il arrive même certaines fois lors de l'affichage d'un dossier ou d'un item qu'un message d'erreur apparaisse quelques secondes avant que le contenu ne soit finalement affiché sans nouvelle action de ma part…

**Comment by barbogogo** [comment]
Merci pour ce retour.
en effet, le timeout est fixé à 10 seconde.
J'ai rencontré ce cas lorsque le réseau data n'était pas de très bonne qualité.
Peut-être que je devrait augmenté cette valeur...

**Comment by kvnco** [comment]
A-t-elle été diminuée dernièrement ?
J'ai certains flux pour lesquels les billets sont assez longs et il semble effectivement qu'on arrive ici à une limite lorsque le réseau n'est pas très bon…
Une solution pourrait également être de le rendre configurable. Même si ça reste technique, et je ne suis donc pas sûr que l'idée soit très intéressante…

**Comment by barbogogo** [comment]
Il y a deux timeout à respecter :
- 10s pour se connecter au serveur
- 10s pour recevoir les informations depuis le serveur

Je vais monter ces données à 20s.

**Comment by kvnco** [comment]
OK, je ferai des tests à la prochaine livraison. Merci.

**Comment by barbogogo** [comment]
Tu peux essayer cette version temporaire si tu le souhaites :smile: 

http://barbogogo.fr/xplorer/data/public/143000.php

**Comment by kvnco** [comment]
"Ooops, the file you required could not be found! Maybe it was deleted or
it is not shared with you anymore"

**Comment by barbogogo** [comment]
http://barbogogo.fr/xplorer/data/public/143000.php

**Comment by agentcobra** [comment]
L'application refonctionne chez moi

**Comment by kvnco** [comment]
C'est bon. Je la teste dans la journée. :)

**Comment by kvnco** [comment]
Bonsoir,

Effectivement, au bout d'une journée ça ne me paraît pas mal du tout. Il reste à voir si ça se confirme sur plusieurs jours.
J'en profite aussi pour dire que j'aime bien l'idée des icônes à gauche, et fragment de l'article (snippet) qui apparaît dans la liste. :)

**Comment by kvnco** [comment]
… par contre, je me demande si c'est une impression, mais j'ai l'impression que le lazy loading est à nouveau HS…

**Comment by barbogogo** [comment]
Bonjour,
Merci @kvnco pour ton retour. J'en conclu que les timeout étaient trop faibles (sauf si tu as eu des soucis depuis...).
Le lazy loading fonctionne chez moi... tu vois des problèmes de chargement des articles ?

**Comment by kvnco** [comment]
Hello,

Je confirme que je trouve toujours ça mieux. Je ferme donc le ticket.
Après test avec un wifi et en monitorant les logs, le lazy-loading fonctionne également mais j'ai quelques remarques. J'ai donc ouvert un autre ticket :  Issue #62 

Merci !

**Comment by barbogogo** [comment]
Ok.
Merci à toi
