### ISSUE TITLE
Erreur dans le décompte des articles non lus

### ISSUE THREAD

**Issue by kvnco** [barbogogo/leedReader#59]
Bonjour,

Il arrive quelques fois que le décompte d'articles non lus soit correct, mais que lorsque je lis ces articles le décompte devienne alors négatif.
J'ai constaté cette erreur 1 à 2 fois par semaine (avec une utilisation quotidienne).

Ex. : 4 articles non lus. Je lis ces 4 articles. Le flux m'indique alors "-4" aritcles non lus.
![screenshot_2013-09-08-11-01-11](https://f.cloud.github.com/assets/2389101/1105469/09c80b9e-1927-11e3-80ed-8bd305234459.png)

Il semble que cette erreur apparaissent de façon aléatoire (je ne suis pas parvenu à déterminer une séquence d'événements la provoquant).

LeedReader v 1.4.5b
Android 4.1.1

**Comment by barbogogo** [comment]
Bonjour @kvnco,
Pour ce problème, je n'ai trouvé qu'un scénario :
- Récupération du nombre d'articles non lus en récupérant le contenu du flux (le compteur d'articles non lus est donc initialisé (à la valeur A)),
- Lecture de tous les articles du flux (le compteur est donc à B),
- Récupération de nouveaux articles via le lazy loading (le compteur reste à B au lieu d'être à la valeur C),
- Lecture de D articles (le compteur est à B-D au lieu de C-D et peut donc être négatif)

Ce cas, existe mais est je pense assez rare, afin de ne pas voir de nombre négatifs, je propose de faire la chose la plus moche au monde :

```
Si compteur < 0 alors
    compteur = 0
Fin Si
```

Je ne ferme pas cette issue en attendant de faire mieux...

**Comment by kvnco** [comment]
Oui, ce n'est pas terrible. ;)

Mais je suis étonné : je suis assez convaincu que lorsque le bug s'est produit, je n'étais pas dans le cas de billets supplémentaires récupérés en lazy-loading…

Par contre, cela fait des semaines que je n'ai pas vu le bug se reproduire. Il est donc possible qu'il ait été déjà corrigé par ailleurs (?).
Quoiqu'il en soit, je suppose que je peux fermer ce ticket.

Quitte à le rouvrir si j'avais quelque chose à y ajouter plus tard… ;)
