### ISSUE TITLE
Amélioration du lazy-loading ?

### ISSUE THREAD

**Issue by kvnco** [barbogogo/leedReader#62]
Bonjour,

Je me suis aperçu qu'avec une connexion data, j'avais quelques difficultés à faire fonctionner le lazy-loading. En regardant les logs serveurs, je constate à chaque appel ces 2 lignes :
/leed/plugins/api/json.php?option=getUnread&nbMaxArticle=50&offset=xx
/leed/plugins/api/json.php?option=getFolders

Des petites questions (suggestions d'améliorations ?)…
- est-il possible de ne ramener que 20 articles à chaque fois ?
- pourquoi recharger la liste des dossiers à chaque appel ?
- ne peut-il pas être nécessaire de gérer une authentification ? est-ce fait ?

Merci

**Comment by barbogogo** [comment]
En effet, on peut réduire à 20 articles, 50 c'est trop.
Effectivement, c'est bête de recharger les répertoires. Toutefois ceci ne doit être vrai que pour la page d'accueil (il faut que je vérifie).
L'authentification est réalisée à l'initialisation et gérée par une session php via l'API.

**Comment by kvnco** [comment]
Je confirme que mon test est fait sur la page d'accueil. :)
Concernant la session : si celle-ci expire, l'authentification est-elle
refaite ou bien le lady-loading cesse-t-il de fonctionner ?

**Comment by barbogogo** [comment]
Bon, en fait les répertoires sont rechargés à chaque fois. A voir quand il est préférable de les recharger.

Si la session expire un message d'erreur devrait apparaitre.

/!\ Le lazy loading ne fonctionne pas en mode hors-connexion (pour le moment).

**Comment by kvnco** [comment]
Je pense que les recharger uniquement lorsque l'on navigue d'un répertoire
à l'autre est suffisant (et déchargera un peu la connexion !)… Mais ça peut
se discuter. :)
