### ISSUE TITLE
Erreur PHP

### ISSUE THREAD

**Issue by SalutAToi** [barbogogo/leedReader#64]
Bonjour, 

J'ai rencontré une erreur PHP en installant leedReader.

Intitulé : "PHP Error"
Texte : """Note[8]Undefined index 4- /volume1/web/leed/plugins/api/json.php(k.183)

Your server configuration :
- PHP Version : 5.3.27
- JSON Version : 1.2.1
  -MYSQL Version : 1.0
  """
  La ligne en question est la suivante : 
                  $feeds2 = $allFeeds['folderMap'][$folder->getId()];

J'ai installé le serveur sur un synology, cela fonctionne correctement.

Est-ce un bug ou un simple problème de configuration ?

D'avance, merci de votre aide.

PS : Une petite suggestion : la possibilité d'accepter des certificats auto signés pour pouvoir se connecter en SSL serait intéressant.

Merci beaucoup pour votre travail

Cordialement,
TheDoctor

**Comment by kvnco** [comment]
Hello @TheDoctorII,

Pour les certifs autosignés, un ticket est ouvert ici : #18

Ensuite l'erreur que tu rencontres ressemble fort à celle-ci barbogogo/leed-API#11  mais elle était normalement corrigée. As-tu bien la dernière version du plugin API ?

updated : corrige le lien vers le ticket

**Comment by SalutAToi** [comment]
Merci, kvnco.

La version de l'API est la 0.9. Il me semble bien qu'il s'agit de la dernière ?

Je ne sais pas si cela correspond à une histoire de caractères (je ne connais ni le PHP ni l'appli :)), mais l'erreur semble venir du fichier json.php. Cela correspond au formatage des caractères ?

**Comment by kvnco** [comment]
Oups.

Il s'agit bien du ticket 11, mais pas sur le bon projet. C'est donc celui-ci barbogogo/leed-API#11 qui t'intéresse. C'est en fait un pb de dossier vide de tout flux (a priori celui comportant l'ID 4).

Le bug est corrigé dans la 0.10, je t'invite à mettre à jour. :)

**Comment by SalutAToi** [comment]
J'ai MàJ (et ajouter du contenu) et ça marche, merci pour l'aide :) .
