### ISSUE TITLE
Retour à la liste des billets, lors du passage d'un billet à l'autre

### ISSUE THREAD

**Issue by kvnco** [barbogogo/leedReader#66]
Hello,

Je teste actuellement la version 1.4.6b et lors de la lecture d'un billet n, si je souhaite passer au billet n+1 en glissant mon doigt sur l'écran de la droite vers la gauche, je reviens sur la liste des billets où les billets n et n+1 sont désormais marqués comme lus.

Cette erreur est nouvelle, reproductible à chaque fois et indépendante du flux affiché.

**Comment by barbogogo** [comment]
arf, c'est embêtant... j'ai fait la correction : [LeedReader_1.4.6c.apk](http://barbogogo.fr/xplorer/data/public/d1f7af.php)

**Comment by kvnco** [comment]
OK, ce bug est corrigé ! :)
