### ISSUE TITLE
SSLPeerUnverifiedException avec certificat SSL bâclé

### ISSUE THREAD

**Issue by Sbgodin** [barbogogo/leedReader#69]
Hello,

Mon hébergement utilise un certificat de base, celui fournit à l'installation du serveur. Il est auto-signé et le nom d'hôte ne correspond pas au nom de domaine.

En _http_ leedReader fonctionne normalement. En _https_ il s'arrête et affiche le message suivant : `javax.net.ssl.SSLPeerUnverifiedException: No peer certificate`

Peut-on être simplement averti que l'admin du serveur est un branque, mais avec la possibilité d'ignorer cette erreur ? À la limite, il suffirait simplement que l'application guette tout changement futur du certificat et prévienne à ce moment-là.

Merci beaucoup !

**Comment by kvnco** [comment]
Hello,

Je pense qu'on rejoins assez largement l'Issue #18

**Comment by Sbgodin** [comment]
Effectivement, ça fait doublon. Au temps pour moi.
