### ISSUE TITLE
[1.5 beta] lecture article glisser du doigt

### ISSUE THREAD

**Issue by cobalt74** [barbogogo/leedReader#73]
Sur la lecture des articles, lorsque je glisse de droite à gauche, je lis l'article puis je passe au suivant.

A partir du 3 ième, il recharge et repasse au 1er article. 

humm il me semble avoir déjà lu cet article !! après 3 tours, j'ai arrêté ... :smile:

**Comment by ghost** [comment]
J'ai eu le même tour au bout du 9e article puis une erreur #3...
Cette erreur revient quelques instants après l'ouverture de n'importe quel article d'ailleurs.

**Comment by barbogogo** [comment]
Salut, problème corrigé dans la prochaine version :smile: 
Elle sera dispo aujourd'hui !

**Comment by cobalt74** [comment]
j'ai plus de soucis pour le moment. good ;)

**Comment by ghost** [comment]
Plus de problème non-plus.
Par contre j'ai une notif de nouvelle version : celle que j'ai déjà...

**Comment by barbogogo** [comment]
Salut, normalement, la notification est sur la révision 1.5.1 et non plus 1.5.
