### ISSUE TITLE
Nouveau logo

### ISSUE THREAD

**Issue by ghost** [barbogogo/leedReader#78]
Il faudrait que leed reader est un logo plus différencié de leed et plus visible dans le menu d'Android.
Je peux m'en charger.
Des idées avant que je ne me lance?

**Comment by barbogogo** [comment]
Salut @misterair,
C'est une eccellente idée et je te fais entièrement confiance :-)
Merci !

**Comment by ghost** [comment]
ok, donc j'ai carte blanche :-)

**Comment by barbogogo** [comment]
Je suis cueieux de voir ce que tu pourrais proposer :smile:

**Comment by ghost** [comment]
Voici le logo v1:

![leeadreaderlogo](https://f.cloud.github.com/assets/4334834/1845606/bf9d11ca-7594-11e3-9c2f-6615940fd817.png)

Tu en penses quoi?

**Comment by cobalt74** [comment]
Salut, joli ! Sur ma tablette nexus 7 toutes les icônes sont carré. Est ce que ça respect le format Android ?

**Comment by barbogogo** [comment]
Salut @misterair,

Parfait pour moi. Merci !!

En effet, il faut maintenant respecter les règles définies dnas le lien suivant : http://developer.android.com/design/style/iconography.html
Mais je reviendrai vers toi :smile:

Il n'y a plus qu'à corriger les bugs et intégrer le logo... je retrouve mon pc ce soir :smile:

**Comment by ghost** [comment]
@cobalt74 du moment que l'image soit carré (avec la transparence) tout va bien. Après beaucoup d'icônes sont carrés. J'avais envie de sortir de cette monotonie ;-)

**Comment by ghost** [comment]
@barbogogo  dès que j'ai le temps je crée une archive avec les icônes dans les diverses résolutions préconisées.
Par contre avec ce nouveau logo tu risques de devoir passer la barre de menu dans une teinte claire (#eee par exemple)...

**Comment by barbogogo** [comment]
@misterair, oui, le design de la barre de menu devra être modifié...
Mais ça me va.

Maintenant que j'ai mon pc, je vais pouvoir être un peu plus bavard (c'est plus compliqué avec le smartphone...). J'ai beaucoup ce nouveau logo qui garde le logo de Leed avec l'ajout de la touche RSS et le cadre noir pour le smartphone :smile:

**Comment by ghost** [comment]
Bizarrement c'est depuis que j'ai installé l'App github que je crée tickets sur tickets au grand dam des dev :D

Pour l'icône je ne pouvais pas faire sans celle de leed. Et je voulais une symbolique forte, quitte à être minimaliste :-)

**Comment by barbogogo** [comment]
:-) j'ai encore du mal avec le clavier tactile pour de long textes...

En tout cas, l'icône est très réussie.

**Comment by ghost** [comment]
Voici le Package d'icones: http://remitaines.fr/160 
J'ai ajouté un .svg avec une icone blanche. ça pourrait peut-être servir pour la barre de notifications d'Android.

**Comment by barbogogo** [comment]
Super, merci !!!
:smile:
