### ISSUE TITLE
[1.5.1 beta] APK en 1.5

### ISSUE THREAD

**Issue by cobalt74** [barbogogo/leedReader#79]
donc on a l'alerte d'une version 1.5.1 disponible en téléchargement à chaque ouverture de LeedReader ;)

**Comment by barbogogo** [comment]
Arf, c'est nul... je me suis planté ?
Voici un nouveau lien : http://barbogogo.fr/xplorer/data/public/b81fd5.php
@cobalt74, @misterair, désolé...

**Comment by ghost** [comment]
Ton lien pointe vers la 1.5.1 qui est concerné par ce problème. Tu as change quelque chose depuis hier ?

**Comment by barbogogo** [comment]
j'ai changé le fichier apk, mais j'aurais pu le mettre en 1.5.2...

**Comment by ghost** [comment]
D'accord. Je teste ça de suite alors.

**Comment by ghost** [comment]
Bug résolu, on peut clore le ticket ;-)

**Comment by barbogogo** [comment]
ok, merci :smile:

**Comment by cobalt74** [comment]
je peux pas tester mais je vous fais confiance :smile:
