### ISSUE TITLE
Favoriser un article lors de sa lecture

### ISSUE THREAD

**Issue by cobalt74** [barbogogo/leedReader#80]
Ajouter un bouton favoriser sur la lecture d'un article.
on est obligé de revenir sur l'écran precedent donc pas frendly.

**Comment by barbogogo** [comment]
En effet, est-ce que via le menu déroulant ça te semble suffisant, ou faudrait-il ajouter un bandeau en haut ou en bas de l'écran ?

**Comment by kvnco** [comment]
+1 et le menu me paraît très bien
En fait, j'ajouterai également le "marquer comme non lu" ou "laisser non lu" pour un billet sur lequel on souhaiterait revenir plus tard.

**Comment by cobalt74** [comment]
est ce que tu peux l'inclure dans la page de l'article en haut à droite ?
permet d'avoir une unicité dans le fonctionnement par rapport à la liste des articles. comme ça, tu peux mettre les deux icônes déjà utilisés (lu/nonlu) et (favoriser/défavoriser)

**Comment by barbogogo** [comment]
Voici une proposition :

![export](https://f.cloud.github.com/assets/4095207/1860356/46bcb920-77b2-11e3-8d7e-9bb1003debbc.png)

On voit les deux icônes (lu/nonlu) et (favoriser/défavoriser) en haut de l'article. Le scroll est réalisé sur tout le contenu de l'article (titre + info de l'article + boutons + contenu de l'article).

**Comment by cobalt74** [comment]
Pour moi c'est plus claire en terme de cohérence. Je valide !

**Comment by barbogogo** [comment]
Aller hop, cadeau : http://barbogogo.fr/xplorer/data/public/b0418b.php

**Comment by cobalt74** [comment]
nice :+1:
