### ISSUE TITLE
Le titre des billets n'est plus cliquable

### ISSUE THREAD

**Issue by kvnco** [barbogogo/leedReader#81]
Bonjour,

Merci pour le 1.5.2 !
Par contre, lors de l'affichage d'un billet, les titres ne sont plus cliquables pour aller sur le site d'origine.

**Comment by barbogogo** [comment]
Bonjour,

Oui, c'est vrai. Je ne l'ai pas mis en place dans un premier temps, je voulais avoir un premier retour le le design présenté. Mais ce sera fait dans la prochaine révision.

Merci !

**Comment by kvnco** [comment]
Pour ma part, je trouve ça pas mal du tout ! :)

**Comment by barbogogo** [comment]
Merci :smile:

**Comment by cobalt74** [comment]
rah mais oui c'est nikel :+1:

**Comment by barbogogo** [comment]
Si tout le monde est d'accord, je ferme le ticket :smile:
