### ISSUE TITLE
Page d'accueil: Ajouter le nom de la source en dessous des titres

### ISSUE THREAD

**Issue by ghost** [barbogogo/leedReader#82]
Actuellement on a la date et l'auteur.  Ce serait mieux d'avoir la date et le nom du flux en dessous des titres des articles.

**Comment by barbogogo** [comment]
Ok, il faudra mettre à jour l'API.

**Comment by barbogogo** [comment]
Voici la proposition :
J'ai gardé l'auteur et ajouté entre parenthèses la source.

exemple pour les flux :
![flux](https://f.cloud.github.com/assets/4095207/1886435/c270298c-79e5-11e3-8d18-02f9bf4d6ead.png)

exemple pour les articles : 
![article](https://f.cloud.github.com/assets/4095207/1886438/c671b974-79e5-11e3-9d3e-dd296bde9f0b.png)

**Comment by ghost** [comment]
J'ai juste un doute pour la place que ça va prendre avec le nom de certains flux. Sinon ça va.

**Comment by barbogogo** [comment]
Ok, voici le fichier apk pour tests et avis :smile:
http://barbogogo.fr/xplorer/data/public/84ac81.php

Ne pas oublier de mettre à jour l'API (seul le fichier json.php a été modifié) :
https://github.com/barbogogo/leed-API/tree/393912eda82cdac6554db00e1c6dfdfd5dce15aa

**Comment by ghost** [comment]
"No value for name feed"
Il va falloir que j'allume un PC et réinstalle l'API pour te confirmer...

**Comment by barbogogo** [comment]
Yes, il faut la nouvelle API...

**Comment by ghost** [comment]
Après réinstallation et réactivation de l'API j'ai toujours la même erreur.

**Comment by barbogogo** [comment]
Tu as l'erreur "No value for nameFeed" avec l'API https://github.com/barbogogo/leed-API/tree/393912eda82cdac6554db00e1c6dfdfd5dce15aa ?

**Comment by ghost** [comment]
Voilà.

**Comment by barbogogo** [comment]
Est-ce que tu peux essayer avec la nouvelle API et [LeedReader v1.7](http://barbogogo.fr/xplorer/data/public/4bb670.php) ?
Puis réessayer avec [LeedReader v1.7.1](http://barbogogo.fr/xplorer/data/public/84ac81.php) demain ?

J'ai déjà vu des problèmes (je ne sais pas à quel niveau) lors de ce type de mise à jour...

**Comment by ghost** [comment]
Ce soir quand je serais sur les PC je retesterais ça. 
C'est bizarre pour l'API car j'ai ré-uploadé tout les fichiers par FTP

**Comment by ghost** [comment]
Réinstallation de l'API depuis un pc, réactivation, ça fonctionne. Et pourtant je n'ai rien fait de plus que ce matin depuis mon smartphone...

**Comment by barbogogo** [comment]
Ok. Merci pour ton retout.
Il y a un probleme de rafraichissement des infos mais je ne sais pas si ça vient du serveur ou du client...
