### ISSUE TITLE
Connection impossible (url invalide)

### ISSUE THREAD

**Issue by bestlibre** [barbogogo/leedReader#87]
Depuis la mise a jour simultanée de leed (version 1.6.1), leed reader (1.8 beta) et de l'api (0.11), je n'arrive plus a me connecter avec leedreader. J'ai a chaque fois le message "URL non valide, merci de la changer"

**Comment by qwertygc** [comment]
:+1:  Moi de même

**Comment by qwertygc** [comment]
Bon, le code sur le Leed Market ne fonctionne pas, il faut utiliser ça https://github.com/barbogogo/leed-API/tree/master/api

**Comment by MassiG** [comment]
à la lecture des sources de l'app. j'ai l'impression qu'il s'agit d'un probleme de casse.

En effet, à la ligne 116 (https://github.com/barbogogo/leedReader/blob/master/LeedReader/src/com/barbogogo/leedreader/APIConnection.java) on peut voir que le chemin est ecrit en dur et en minuscule  (/plugins/api). 
L'intitulé du dossier contenu dans le leed-market est, lui, en capitale. 

Il est possible que le problème vienne de là.

**Comment by barbogogo** [comment]
Bonjour,

Il y a en effet un problème de nommage sur le leed market. Il faut mettre api en minuscule.

**Comment by ashemsay** [comment]
J'ai modifié API en api, mais ça ne résoud pas le problème pour moi.
J'utilise un reverse proxy mais j'accède bien à http://mondomaine.fr/Leed/plugins/api/.

**Comment by barbogogo** [comment]
Bonjour

Vous avez pris les sources du leed-market ?
Quel est le problème remonté ?

**Comment by ashemsay** [comment]
Bonjour, 

Oui j'ai pris les sources du leed-market et renommé le répertoire API en api comme indiqué plus haut dans .
Le problème est que lorsque j'entre l'adresse de mon serveur ainsi que l'identifiant et la clé API dans l'application et que je veux sortir des paramètres j'obtiens le message "URL non valide, merci de la changer".
J'entre l'URL complète de mon Leed, http://mon.domaine.fr/Leed. J'ai essayé avec ou sans slash à la fin, ça ne change rien

**Comment by barbogogo** [comment]
Merci pour ces détails. 

Le répertoire api est bien dans le répertoire plugin avec les droits en écriture pour le serveur et la clé API configurée?

**Comment by ashemsay** [comment]
Oui il est bien dans le répertoire plugins, apache a les droits en écriture. 
Qu'est-ce que vous entendez par "la clé API configurée"? Le plugin Leed API est bien activé et fournit bien la clé nécessaire pour la connexion; clé que j'ai bien renseignée dans l'application Leed Reader.

**Comment by bestlibre** [comment]
Le renommage a marché pour moi, mais il a fallu que je désactive/réactive le plugin pour que ça marche. Avant cette désactivation/réactivation, j'obtenais un message d'erreur (authentification non valide).

**Comment by barbogogo** [comment]
Bonjour,

Est-ce que votre prblème est résolu ?
