### ISSUE TITLE
[bug] Flux effacés

### ISSUE THREAD

**Issue by Neurozone** [barbogogo/leedReader#89]
Bonjour.

Je voulais faire le test avec leeedreader, j'ai donc installé l'ap, renomé le dossier API en api, installé leedreader, synchronisé, et là plus rien, tous mes flux envolés. Je suis grognon.

**Comment by barbogogo** [comment]
Bonjour, 

Merci pour votre retour.
LeedReader ne modifie pas la liste des flux. Il ne modifie que le statut de lecture ou de mise en favori d'un article.
Est ce que vous avez retrouvé vis flux ? Est ce que vous avez pu troiver l'origine ?
