### ISSUE TITLE
APK plus dispo

### ISSUE THREAD

**Issue by kvnco** [barbogogo/leedReader#90]
Hello,

Le lien vers l'APK sur barbogogo.fr/xplorer semble HS.
Est-il possible de le remettre à dispo qqpart ?

Merci

Kevin

**Comment by barbogogo** [comment]
Bonjour Kevin,
Le lien vers l'APK a été mis à jour sur le site : http://www.barbogogo.fr/pydio/data/public/ee8227

Désolé pour ce problème technique...

**Comment by kvnco** [comment]
Merci :)
